export const LOAD_PRICES_REQUEST = 'LOAD_PRICES_REQUEST'
export const LOAD_PRICES_RESULT = 'LOAD_PRICES_RESULT'
export const STOP_WATCHING_CURRENCY_REQUEST = 'STOP_WATCHING_CURRENCY_REQUEST'
export const SET_START_WATCHING_CURRENCY = 'SET_START_WATCHING_CURRENCY'
