export const LOAD_PRICES_REQUEST = 'LOAD_PRICES_REQUEST'
export const LOAD_PRICES_RESULT = 'LOAD_PRICES_RESULT'
export const START_WATCHING_CURRENCY_REQUEST = 'START_WATCHING_CURRENCY_REQUEST'
export const START_WATCHING_CURRENCY_RESPONSE =
  'START_WATCHING_CURRENCY_RESPONSE'
export const STOP_WATCHING_CURRENCY_REQUEST = 'STOP_WATCHING_CURRENCY_REQUEST'
export const SET_FORM_VALUE = 'SET_FORM_VALUE'
