import LOAD_PRICES_REQUEST from './LOAD_PRICES_REQUEST'
import START_WATCHING_CURRENCY_REQUEST from './START_WATCHING_CURRENCY_REQUEST'

export default {
  LOAD_PRICES_REQUEST,
  START_WATCHING_CURRENCY_REQUEST
}
