import LOAD_PRICES_RESULT from './LOAD_PRICES_RESULT'
import SET_FORM_VALUE from './SET_FORM_VALUE'
import STOP_WATCHING_CURRENCY_REQUEST from './STOP_WATCHING_CURRENCY_REQUEST'

export default {
  LOAD_PRICES_RESULT,
  SET_FORM_VALUE,
  STOP_WATCHING_CURRENCY_REQUEST
}
